# Generated by Django 4.1.7 on 2023-03-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_post_id_liked_post_rename_user_id_liked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='post',
        ),
        migrations.AddField(
            model_name='liked',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liked',
            name='post_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
