# Generated by Django 4.1.7 on 2023-03-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_liked_no_of_likes_post_no_of_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed_user_id',
            new_name='followed_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower_user_id',
            new_name='follower_user',
        ),
    ]
